name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
      - name: Set Git identity
        run: |
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "CI Bot"

      - name: Deploy to GitHub Pages
        env:
          NG_CLI_ANALYTICS: "false"
          GH_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
        run: npx ng deploy --base-href=/portfolio-angular/ --no-silent
